apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: append-greeting-task
spec:
  params:
    - name: previous-greeting
      description: The greeting message from the previous task.
      type: string
  results:
    - name: final-greeting
      description: The appended greeting message.
  steps:
    - name: append-message
      image: ubuntu:latest # Or any image with bash
      script: |
        #!/usr/bin/env bash
        PREVIOUS_MESSAGE=$(params.previous-greeting)
        FINAL_MESSAGE="${PREVIOUS_MESSAGE} Goodbye from Stage 2!"
        echo "Stage 2 Appended Message: ${FINAL_MESSAGE}"
        echo -n "${FINAL_MESSAGE}" > "$(results.final-greeting.path)"