apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: greeting-pipeline-run
spec:
  pipelineRef:
    name: greeting-pipeline
  serviceAccountName: pipeline-runner 
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
