apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: transform-message-task
spec:
  params:
    - name: case-option
      type: string
  steps:
    - name: transform
      image: python:3.11-slim
      script: |
        #!/usr/bin/env python3
        import os

        message = "The quick brown fox jumps over the lazy dog."
        choice = os.environ.get("CASE_OPTION", "lowercase")

        if choice == "uppercase":
            transformed = message.upper()
        else:
            transformed = message.lower()

        print("Transformed Message:")
        print(transformed)
      env:
        - name: CASE_OPTION
          value: "$(params.case-option)"
