apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: message-transform-pipeline
spec:
  params:
    - name: case-option
      type: string
      description: "Choose how to transform the message"
      default: lowercase
  tasks:
    - name: transform-message
      taskRef:
        name: transform-message-task
      params:
        - name: case-option
          value: $(params.case-option)
