apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: show-final-message
spec:
  params:
    - name: final-message
      type: string
  steps:
    - name: print
      image: ubuntu:latest
      script: |
        #!/bin/bash
        echo "-----------------------------------------------"
        echo "Final Transformed Message: $(params.final-message)"
        echo "-----------------------------------------------"
