# pipeline-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipeline-role
rules:
- apiGroups: ["tekton.dev"]
  resources: ["tasks", "clustertasks"]
  verbs: ["get", "list"]