# calculate-sum-task.yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: calculate-sum-task
spec:
  workspaces:
    - name: shared # This task uses the shared workspace to read numbers and write sum
  steps:
    - name: calculate-sum
      image: ubuntu:latest # Using ubuntu for bash features
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        # Read the numbers from the shared workspace
        INPUT_NUMBERS=$(cat /workspace/shared/numbers.txt)
        SUM=0

        echo "Calculating sum of numbers from: ${INPUT_NUMBERS}"

        # Split the string by comma and iterate
        IFS=',' read -ra ADDR <<< "$INPUT_NUMBERS"
        for i in "${ADDR[@]}"; do
          SUM=$((SUM + i))
        done

        echo "Calculated Sum: ${SUM}"
        # Write the sum to a file in the shared workspace
        echo -n "${SUM}" > /workspace/shared/calculated_sum.txt
