# define-data-task.yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: define-data-task
spec:
  workspaces:
    - name: shared # This task uses the shared workspace
  steps:
    - name: set-initial-data
      image: alpine:latest # Using a lightweight image for a simple shell command
      script: |
        #!/usr/bin/env sh
        echo "--- Input Number Data ---"
        echo "Numbers to process: 10,25,5,15,30"
        echo "-------------------------"
        # Write the numbers to a file in the shared workspace
        echo "10,25,5,15,30" > /workspace/shared/numbers.txt
