apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: number-sum-run
spec:
  pipelineRef:
    name: number-sum-pipeline
  serviceAccountName: pipeline-runner 
  workspaces:
    - name: shared 
      volumeClaimTemplate:
        spec: 
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi