apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: number-sum-run
spec:
  pipelineRef:
    name: number-sum-pipeline
  workspaces:
    - name: shared
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
