apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: calculate-sum
spec:
  workspaces:
    - name: shared
  steps:
    - name: sum
      image: alpine
      script: |
        #!/bin/sh
        numbers=$(cat $(workspaces.shared.path)/number_string.txt)
        echo "Calculating sum of: $numbers"
        sum=0
        IFS=','; for n in $numbers; do
          sum=$((sum + n))
        done
        echo "DEBUG: Writing sum ($sum) to file"
        echo "$sum" > $(workspaces.shared.path)/calculated_sum.txt
