apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: number-sum-pipeline
spec:
  workspaces:
    - name: shared
  tasks:
    - name: define
      taskRef:
        name: define-data
      workspaces:
        - name: shared
          workspace: shared

    - name: calculate
      runAfter: [define]
      taskRef:
        name: calculate-sum
      workspaces:
        - name: shared
          workspace: shared

    - name: format
      runAfter: [calculate]
      taskRef:
        name: format-final-string
      workspaces:
        - name: shared
          workspace: shared

    - name: print
      runAfter: [format]
      taskRef:
        name: print-final-result
      workspaces:
        - name: shared
          workspace: shared
