apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: define-data
spec:
  workspaces:
    - name: shared
  steps:
    - name: define
      image: alpine
      script: |
        #!/bin/sh
        echo "--- Input Number Data ---"
        echo "Numbers to process: 10,25,5,15,30"
        echo "-------------------------"
        echo "10,25,5,15,30" > $(workspaces.shared.path)/number_string.txt
