apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: calculate-sum
spec:
  params:
    - name: number-string
      description: Comma-separated numbers
  results:
    - name: calculated-sum
      description: The total sum
  steps:
    - name: sum
      image: ubuntu:latest
      script: |
        #!/bin/bash
        numbers="$(params.number-string)"
        sum=0
        IFS=',' read -ra num_array <<< "$numbers"
        for n in "${num_array[@]}"; do
          sum=$((sum + n))
        done
        echo "Calculated Sum: $sum"
        echo -n "$sum" > $(results.calculated-sum.path)