apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: format-final-string
spec:
  workspaces:
    - name: shared
  steps:
    - name: format
      image: alpine
      script: |
        #!/bin/sh
        numbers=$(cat $(workspaces.shared.path)/number_string.txt)
        sum=$(cat $(workspaces.shared.path)/calculated_sum.txt)
        final="Original Numbers: [$numbers] | Total Sum: $sum"
        echo "Formatted String: $final"
        echo "$final" > $(workspaces.shared.path)/final_result.txt
