apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: print-message
spec:
  workspaces:
    - name: shared-data
  steps:
    - name: print
      image: alpine
      script: |
        #!/bin/sh
        echo "Final message:"
        cat $(workspaces.shared-data.path)/message.txt
