apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-greeting
spec:
  results:
    - name: message
  steps:
    - name: create
      image: ubuntu:latest
      script: |
        #!/bin/bash
        echo -n "Hello from Stage 1!" > $(results.message.path)
