apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-greeting
spec:
  workspaces:
    - name: shared-data
  steps:
    - name: write-greeting
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello from Stage 1!" > $(workspaces.shared-data.path)/message.txt
