apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: append-greeting
spec:
  workspaces:
    - name: shared-data
  steps:
    - name: append
      image: alpine
      script: |
        #!/bin/sh
        echo " Goodbye from Stage 2!" >> $(workspaces.shared-data.path)/message.txt
