apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: greeting-pipeline
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: create
      taskRef:
        name: create-greeting
      workspaces:
        - name: shared-data
          workspace: shared-data

    - name: append
      runAfter: [create]
      taskRef:
        name: append-greeting
      workspaces:
        - name: shared-data
          workspace: shared-data

    - name: print
      runAfter: [append]
      taskRef:
        name: print-message
      workspaces:
        - name: shared-data
          workspace: shared-data
