apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: greeting-pipeline-run
spec:
  pipelineRef:
    name: greeting-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        metadata:
          name: shared-data-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
