# message-transformation-pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: message-transformation-pipeline
spec:
  params:
    - name: CASE_OPTION
      description: 'Choose how to transform the message: uppercase or lowercase'
      type: string
      default: "uppercase" # Default choice from Jenkins
      # In Tekton, you'd typically handle choices via documentation or external validation
      # allowedValues: ["uppercase", "lowercase"] # Not standard Tekton syntax, for documentation only

    - name: DEFAULT_MESSAGE
      description: The default message to be transformed.
      type: string
      default: "The quick brown fox jumps over the lazy dog." # Default from Jenkins environment

  tasks:
    - name: apply-transformation-step
      taskRef:
        name: apply-transformation-task # References the standalone Task definition
      params:
        - name: default-message
          value: $(params.DEFAULT_MESSAGE) # Pass PipelineParam to TaskParam
        - name: case-option
          value: $(params.CASE_OPTION) # Pass PipelineParam to TaskParam

  # No explicit 'post' equivalent needed here since the Jenkinsfile only had 'echo' in post.always.
  # If there were more complex post-actions, a 'finally' block would be used.