# uppercase-run.yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: uppercase-message-run
spec:
  pipelineRef:
    name: message-transformation-pipeline
  params:
    - name: CASE_OPTION
      value: "uppercase" # Overrides default, forces uppercase