apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: string-transformation-pipeline
spec:
  params:
    - name: chosen-transformation
      description: The transformation selected by the user.
      type: string
      default: "Uppercase" # A default for convenience, or you can require it to be set by the PipelineRun
      # Tekton doesn't have native dropdown, so we'll rely on PipelineRun param validation
      # In a real scenario, you might have a custom controller or UI to enforce allowed values.

  tasks:
    - name: apply-user-transformation
      taskRef:
        name: transform-string-task
      params:
        - name: user-transformation-choice
          value: $(params.chosen-transformation)
        # initial-message will use its default in the task, or you could pass it explicitly:
        # - name: initial-message
        #   value: "Your custom starting text"

  finally:
    - name: print-final-output
      taskSpec:
        params:
          - name: message-to-hash
            description: The final processed string for hashing.
            type: string
        steps:
          - name: echo-output
            image: ubuntu:latest # Or any image with 'echo'
            script: |
              #!/usr/bin/env bash
              echo "--- Raw Final String for Cross-Platform SHA Hashing ---"
              echo "$(params.message-to-hash)"
              echo "------------------------------------------------------"
      params:
        - name: message-to-hash
          value: $(tasks.apply-user-transformation.results.final-processed-string)